### ISSUE TITLE
Investigate if building addons is compatible with Windows

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat-reporter-extensions#106]
I don't actually know if it is!

To tackle this bug, you'll need a Windows development environment and try to follow the instructions for building and running tests @ https://github.com/webcompat/webcompat-reporter-extensions/blob/master/README.md#building

You'll want to make note of any errors, and ideally send a pull request fixing the issues, ensuring it's still possible to build on macOS and linux (I can help verify those once a PR is made).

**Comment by miketaylr** [comment]
(tagging as unknown *and* medium... in the off chance it just works, we can just close this. but if it doesn't, it won't be an easy bug)

**Comment by deeptibaghel** [comment]
npm install had few warnings - at bottom of this post. Otherwise it worked well on windows.
Below is the output :

E:\webcompat-reporter-extensions-master>**npm run firefox** --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'firefox',
npm verb cli   '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.10.3
npm verb run-script [ 'prefirefox', 'firefox', 'postfirefox' ]
npm info lifecycle webcompat-reporter-addon@0.5.1~prefirefox: webcompat-reporter-addon@0.5.1
npm info lifecycle webcompat-reporter-addon@0.5.1~firefox: webcompat-reporter-addon@0.5.1

> webcompat-reporter-addon@0.5.1 firefox E:\webcompat-reporter-extensions-master
> web-ext run --source-dir=dist/firefox

Running web extension from E:\webcompat-reporter-extensions-master\dist\firefox
Use --verbose or open Tools > Web Developer > Browser Console to see logging
Installed E:\webcompat-reporter-extensions-master\dist\firefox as a temporary add-on
The extension will reload if any source file changes
Press R to reload (and Ctrl-C to quit)
--------------------------------------------------------------------
**E:\webcompat-reporter-extensions-master>npm run test**

> webcompat-reporter-addon@0.5.1 test E:\webcompat-reporter-extensions-master
> intern

√ node - dist output - has shared output (0.001s)
√ node - manifest.json creation - has shared keys (0.008s)
√ node - manifest.json creation - has version number (0.002s)
√ node - manifest.json creation - has application keys (0.001s)
TOTAL: tested 1 platforms, 4 passed, 0 failed


E:\webcompat-reporter-extensions-master>**npm install**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\@theintern\digdug\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\addons-linter\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\boxen\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\decompress\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\decompress-unzip\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\firefox-profile\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\handlebars\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\dispensary\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'E:\webcompat-reporter-extensions-master\node_modules\addons-linter\node_modules\webpack\package.json'
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.

**Comment by miketaylr** [comment]
OK, cool! Thank you @deeptibaghel, it seems like there isn't anything else to do here.
